baseURL = 'https://ildenir.github.io'
languageCode = 'pt-BR'
title = 'Ildenir Barbosa'
theme = 'hyde'

[params]
  description="Bem-vindo! Este é um espaço dedicado a compartilhar ideias, descobertas e etc."

[Menus]
  main = [{Name="About", URL = "about"}, {Name="Tags", URL="/tags"}]
